# Generated by Django 6.1 on 2026-09-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Subtotal')),
                ('shipping', models.PositiveIntegerField(default=0, verbose_name='Costo de Envío')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('items_data', models.JSONField(default=list, verbose_name='Productos del pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(choices=[('juguetes', 'Juguetes'), ('electrónica', 'Electrónica'), ('libros', 'Libros')], default='juguetes', max_length=50, verbose_name='Categoría')),
                ('price', models.PositiveIntegerField(verbose_name='Precio (CLP)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-id'],
            },
        ),
    ]
