# Generated by Django 6.1 on 2026-09-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('city', models.CharField(blank=True, default='Chile', max_length=100, verbose_name='Ciudad / Región')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Calificación (1-5)')),
                ('comment', models.TextField(verbose_name='Comentario o experiencia')),
                ('avatar', models.CharField(blank=True, default='👤', max_length=20, verbose_name='Avatar / Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Testimonio / Reseña',
                'verbose_name_plural': 'Testimonios / Reseñas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Archivo de imagen (JPEG/PNG)'),
        ),
    ]
